version: 1.0.{build}
image: Visual Studio 2017

before_build:
 - nuget restore
 - choco install msbuild-sonarqube-runner
 #- choco install opencover
 - choco install opencover.portable
 - choco install codecov

build_script:
 - MSBuild.SonarQube.Runner.exe begin /k:"EternalArrowBackup" /d:"sonar.organization=inga-lovinde-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%SONAR_LOGIN%"
 - msbuild /t:Rebuild EternalArrowBackup.sln
 - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONAR_LOGIN%"

test_script:
 - dotnet build /t:Rebuild /p:DebugType=full /p:DebugSymbols=true EternalArrowBackup.sln
 - ps: Get-ChildItem *.Tests.csproj -Recurse | % {C:\ProgramData\chocolatey\lib\opencover.portable\tools\OpenCover.Console -register -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --no-build --logger:trx;LogFileName=results.trx --filter Category!=Integration $_" -filter:"+[*]* -[*.Tests]*" -mergeoutput -output:OpenCover.xml -oldStyle}
 - codecov -f OpenCover.xml
